name: Update public Postman collection

on:
  push:
    branches: [ main ]

env:
  COLLECTION_ID: ${{ vars.COLLECTION_ID }}
  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

jobs:
  update_public_collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prepare collection to send
        run: |
          echo "{\"collection\": $(cat postman/collections/OctopusAPI.json)}" > /tmp/OctopusAPI.json

      - name: Update the collection
        run: |
          curl --location -x PUT \
            "https://api.getpostman.com/collections/{{ env.COLLECTION_ID }}" \
            -H "X-Api-Key: {{ env.POSTMAN_API_KEY }}" \
            -H 'Content-Type: application/json' \
            --data @/tmp/OctopusAPI.json
